/*
 * Contains all constants for F1 2023.
 */
package v23

import "github.com/moon36/f1-game-telemetry/src/internal/packets"

const PACKET_FORMAT_ID uint16 = 2023

var PACKET_TOPIC_MAP = map[uint8]string{
	CAR_MOTION_DATA_ID:           packets.TOPIC_CAR_MOTION_DATA,
	SESSION_DATA_ID:              packets.TOPIC_SESSION_DATA,
	LAP_DATA_ID:                  packets.TOPIC_LAP_DATA,
	EVENT_DATA_ID:                packets.TOPIC_EVENT_DATA,
	PARTICIPANTS_DATA_ID:         packets.TOPIC_PARTICIPANT_DATA,
	CAR_SETUP_DATA_ID:            packets.TOPIC_CAR_SETUP_DATA,
	CAR_TELEMETRY_DATA_ID:        packets.TOPIC_CAR_TELEMETRY_DATA,
	CAR_STATUS_DATA_ID:           packets.TOPIC_CAR_STATUS_DATA,
	FINAL_CLASSIFICATION_DATA_ID: packets.TOPIC_FINAL_CLASSIFICATION_DATA,
	LOBBY_INFO_DATA_ID:           packets.TOPIC_LOBBY_INFO_DATA,
	CAR_DAMAGE_DATA_ID:           packets.TOPIC_CAR_DAMAGE_DATA,
	SESSION_HISTORY_DATA_ID:      packets.TOPIC_SESSION_HISTORY_DATA,
	TYRE_SET_DATA_ID:             packets.TOPIC_TYRE_SET_DATA,
	CAR_MOTION_EX_DATA_ID:        packets.TOPIC_CAR_MOTION_EX_DATA,
}

// === Packet IDs from the packetId field in the header ===
const CAR_MOTION_DATA_ID = 0
const SESSION_DATA_ID = 1
const LAP_DATA_ID = 2
const EVENT_DATA_ID = 3
const PARTICIPANTS_DATA_ID = 4
const CAR_SETUP_DATA_ID = 5
const CAR_TELEMETRY_DATA_ID = 6
const CAR_STATUS_DATA_ID = 7
const FINAL_CLASSIFICATION_DATA_ID = 8
const LOBBY_INFO_DATA_ID = 9
const CAR_DAMAGE_DATA_ID = 10
const SESSION_HISTORY_DATA_ID = 11
const TYRE_SET_DATA_ID = 12
const CAR_MOTION_EX_DATA_ID = 13

// === Packet sizes ===
const CAR_MOTION_DATA_SIZE = 1349
const SESSION_DATA_SIZE = 644
const LAP_DATA_SIZE = 1131
const EVENT_DATA_SIZE = 45
const PARTICIPANT_DATA_SIZE = 1306
const CAR_SETUP_DATA_SIZE = 1107
const CAR_TELEMETRY_DATA_SIZE = 1352
const CAR_STATUS_DATA_SIZE = 1239
const FINAL_CLASSIFICATION_DATA_SIZE = 1020
const LOBBY_INFO_DATA_SIZE = 1218
const CAR_DAMAGE_DATA_SIZE = 953
const SESSION_HISTORY_DATA_SIZE = 1460
const TYRE_SET_DATA_SIZE = 231
const CAR_MOTION_EXT_DATA_SIZE = 217
