version: '3.8'

services:
  telemetry-receiver:
    user: "1000:1000"
    container_name: Telemetry-Receiver
    environment:
      - PORT=${UDP_PORT}
    build:
      context: ./src/udp-server
      dockerfile: Dockerfile
    ports:
      - "${UDP_PORT}:${UDP_PORT}/udp"
    restart: unless-stopped