services:
  telemetry-receiver:
    user: "1000:1000"
    container_name: Telemetry-Receiver
    build:
      context: .
      dockerfile: src/udp-server/Dockerfile
    environment:
      - PORT=${UDP_PORT}
      - KAFKA_ADDRESS=${KAFKA_ADDRESS}
      - KAFKA_PORT=${KAFKA_PORT}
    ports:
      - "${UDP_PORT}:${UDP_PORT}/udp"
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_healthy

  kafka:
    image: apache/kafka:latest
    container_name: Kafka
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    volumes:
      - kafka_data:/apache/kafka
    environment:
      # KRaft settings
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka:${KAFKA_CONTROLLER_PORT}

      # Listeners
      - KAFKA_LISTENERS=PLAINTEXT://:${KAFKA_PORT},CONTROLLER://:${KAFKA_CONTROLLER_PORT}
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_ADDRESS}:${KAFKA_PORT}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      # Topic settings
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_NUM_PARTITIONS=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_MIN_IN_SYNC_REPLICAS=1
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  dashboard:
    container_name: Dashboard
    build:
      context: src/dashboard/
      dockerfile: Dockerfile
    environment:
      - DASHBOARD_PORT=${DASHBOARD_PORT}
      - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - "${DASHBOARD_PORT}:${DASHBOARD_PORT}"
    restart: unless-stopped

  backend:
    container_name: Backend
    build:
      context: src/backend
      dockerfile: Dockerfile
    environment:
      - KAFKA_ADDRESS=${KAFKA_ADDRESS}
      - KAFKA_PORT=${KAFKA_PORT}
      - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      kafka:
        condition: service_healthy

  database:
    container_name: Database
    image: redis:alpine
    volumes:
      - ./database/users/users.acl:/etc/redis/users.acl:ro
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: ["redis-server", "--aclfile", "/etc/redis/users.acl"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  db-manager:
    container_name: DB-Manager
    build:
      context: .
      dockerfile: src/database/Dockerfile
    environment:
      - KAFKA_ADDRESS=${KAFKA_ADDRESS}
      - KAFKA_PORT=${KAFKA_PORT}
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      kafka:
        condition: service_healthy

volumes:
  kafka_data:
    driver: local
