export enum TyreCompounds {
    C5 = 'C5',
    C4 = 'C4',
    C3 = 'C3',
    C2 = 'C2',
    C1 = 'C1',
    C0 = 'C0',
    INTERMEDIATE = 'Intermediate',
    WET = 'Wet',
    SUPERSOFT = 'Super Soft',
    DRY = 'Dry',
    SOFT = 'Soft',
    MEDIUM = 'Medium',
    HARD = 'Hard',
    UNKNOWN = 'Unknown',
}