name: Pylint

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ${{ github.workspace }}/src/backend/requirements.txt ]; then pip install -r ${{ github.workspace }}/src/backend/requirements.txt; fi
        pip install pylint
    - name: Analysing backend with pylint
      run: |
        pylint --rcfile=${{ github.workspace }}/.github/workflows/.pylintrc $(git ls-files 'src/backend/*.py')
